from src.agents.daily_note_linker import DailyNoteLinker


def test_daily_note_linker_adds_connections_before_marker():
    content = (
        "# Daily Journal: 2026-08-29\n\n"
        "---\n*Generated by Autograph Agent*\n"
    )
    connections = (
        "## Connected graph\n"
        "- **Agents:** [[agents/Ollama|Ollama]], [[agents/Copilot|Copilot]]"
    )

    updated = DailyNoteLinker._insert_connections(content, connections)

    assert connections in updated
    assert updated.index(connections) < updated.index("*Generated by Autograph Agent*")


def test_daily_note_linker_leaves_note_unchanged_without_new_connections():
    content = "# Daily Journal: 2026-08-29\n\n---\n*Generated by Autograph Agent*"

    assert DailyNoteLinker._insert_connections(content, "") == content
