from pathlib import Path
from typing import Any, Dict, Iterable, List


def _clean_link_text(value: str) -> str:
    return value.replace("[", "").replace("]", "").replace("|", "-").strip()


def daily_note_link(date: str) -> str:
    return f"[[daily_notes/{date}|{date}]]"


def commit_note_link(commit: Dict[str, str]) -> str:
    project = commit["project"].replace(" ", "_").replace("/", "_")
    commit_id = commit["id"]
    title = _clean_link_text(commit["title"])
    return (
        f"[[projects/{project}/commits/{commit_id}|"
        f"{commit_id[:12]} {title}]]"
    )


def render_daily_note(
    date: str,
    summary: str,
    sections: Iterable[Dict[str, Any]],
    commits: List[Dict[str, str]],
    related_dates: Iterable[str],
) -> str:
    """Render a technical daily note with stable links to related vault notes."""
    commits_by_id = {
        commit["id"]: commit for commit in commits
    }
    commits_by_id.update(
        {commit["id"][:12]: commit for commit in commits}
    )
    lines = [
        f"# Daily Journal: {date}",
        "",
        "## Day summary",
        summary.strip(),
    ]

    if commits:
        lines.extend(["", "## Commits"])
        lines.extend(f"- {commit_note_link(commit)}" for commit in commits)

    lines.extend(["", "## Technical notes"])
    for index, section in enumerate(sections, start=1):
        title = _clean_link_text(str(section.get("title") or f"Work item {index}"))
        lines.extend(
            [
                "",
                f"### {title}",
                "",
                "**What was done**",
                str(section.get("work_done") or "No implementation detail captured.").strip(),
                "",
                "**What went well**",
                str(section.get("went_well") or "Not recorded.").strip(),
                "",
                "**What we learned**",
                str(section.get("learned") or "Not recorded.").strip(),
                "",
                "**Worth remembering**",
                str(section.get("remember") or "Not recorded.").strip(),
            ]
        )
        section_commit_ids = section.get("commits")
        if not isinstance(section_commit_ids, list):
            section_commit_ids = []
        section_commits = [
            commits_by_id[commit_id]
            for commit_id in section_commit_ids
            if isinstance(commit_id, str) and commit_id in commits_by_id
        ]
        if not section_commits:
            section_commits = commits
        if section_commits:
            lines.extend(["", "**Related commits**"])
            lines.extend(f"- {commit_note_link(commit)}" for commit in section_commits)

    related_links = [daily_note_link(related_date) for related_date in related_dates]
    if related_links:
        lines.extend(["", "## Related notes"])
        lines.extend(f"- {link}" for link in related_links)

    lines.extend(["", "---", "*Generated by Autograph Agent*"])
    return "\n".join(lines) + "\n"


def related_daily_dates(notes_dir: Path, date: str) -> List[str]:
    """Find the immediately adjacent existing daily notes for navigation."""
    dates = sorted(
        note_path.stem
        for note_path in notes_dir.glob("*.md")
        if note_path.stem != date
    )
    previous = [candidate for candidate in dates if candidate < date]
    following = [candidate for candidate in dates if candidate > date]
    related = []
    if previous:
        related.append(previous[-1])
    if following:
        related.append(following[0])
    return related
