import json
import os
import subprocess
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

from config.settings import Config
from src.agents.sync_agent import AutographSyncAgent
from src.core.drivers.jsonl_session_driver import (
    ClaudeDriver,
    CodexDriver,
    CopilotDriver,
    JsonlSessionDriver,
    PiDriver,
)
from src.core.synthesizer import Synthesizer, SynthesizerError
from src.core.daily_note_renderer import render_daily_note
from src.core.vault import VaultManager


class DailyBackfillAgent:
    """Creates date-specific daily notes from retained local work records."""

    generated_marker = "*Generated by Autograph Agent*"
    max_prompt_characters = 12000

    def __init__(self):
        self.config = Config()
        self.vault_manager = VaultManager(self.config.VAULT_ROOT)
        self.synthesizer = Synthesizer()
        self.sync_agent = AutographSyncAgent(self.vault_manager.vault_root)
        self.drivers = [
            CopilotDriver("copilot", self.config),
            ClaudeDriver("claude", self.config),
            CodexDriver("codex", self.config),
            PiDriver("pi", self.config),
        ]

    @staticmethod
    def _repositories(search_dir: Path) -> List[Path]:
        repositories = []
        for root, directories, _ in os.walk(search_dir):
            if ".git" in directories:
                repositories.append(Path(root))
                directories.remove(".git")
            directories[:] = [
                directory
                for directory in directories
                if directory not in {"node_modules", "__pycache__", ".venv"}
            ]
        return repositories

    @staticmethod
    def _commits_for_date(
        repositories: Iterable[Path], date: str
    ) -> List[Dict[str, str]]:
        next_date = (
            datetime.fromisoformat(date).replace(tzinfo=timezone.utc)
            + timedelta(days=1)
        ).date().isoformat()
        commits = []
        for repository in repositories:
            try:
                result = subprocess.run(
                    [
                        "git",
                        "-C",
                        str(repository),
                        "log",
                        f"--since={date}T00:00:00",
                        f"--until={next_date}T00:00:00",
                        "--pretty=format:%H%x00%s%x00",
                    ],
                    capture_output=True,
                    text=True,
                    check=True,
                )
            except subprocess.CalledProcessError as error:
                print(f"⚠️ Could not read commits from {repository.name}: {error}")
                continue
            fields = result.stdout.split("\0")
            commits.extend(
                {
                    "id": fields[index],
                    "title": fields[index + 1],
                    "project": repository.name,
                }
                for index in range(0, len(fields) - 1, 2)
                if fields[index].strip() and fields[index + 1].strip()
            )
        return commits

    @staticmethod
    def _group_events_by_date(
        events: Iterable[Dict[str, object]]
    ) -> Tuple[Dict[str, List[Dict[str, object]]], int]:
        grouped = defaultdict(list)
        skipped = 0
        for event in events:
            timestamp = JsonlSessionDriver._parse_timestamp(event.get("timestamp"))
            if timestamp is None:
                skipped += 1
                continue
            grouped[timestamp.date().isoformat()].append(event)
        for day_events in grouped.values():
            day_events.sort(key=lambda event: str(event.get("timestamp", "")))
        return grouped, skipped

    @classmethod
    def _event_chunks(
        cls, events: List[Dict[str, object]]
    ) -> List[List[Dict[str, object]]]:
        chunks = []
        chunk = []
        chunk_length = 0
        for event in events:
            line_length = len(json.dumps(event, ensure_ascii=False))
            if chunk and chunk_length + line_length > cls.max_prompt_characters:
                chunks.append(chunk)
                chunk = []
                chunk_length = 0
            chunk.append(event)
            chunk_length += line_length
        if chunk:
            chunks.append(chunk)
        return chunks

    def _remove_generated_notes(self, dates: Iterable[str] = None) -> int:
        notes_dir = self.vault_manager.vault_root / "daily_notes"
        if not notes_dir.exists():
            return 0

        target_dates = set(dates) if dates is not None else None
        removed = 0
        for note_path in notes_dir.glob("*.md"):
            if target_dates is not None and note_path.stem not in target_dates:
                continue
            content = note_path.read_text(encoding="utf-8", errors="replace")
            if self.generated_marker in content:
                note_path.unlink()
                removed += 1
        return removed

    def _has_generated_note(self, date: str) -> bool:
        note_path = self.vault_manager.vault_root / "daily_notes" / f"{date}.md"
        if not note_path.exists():
            return False
        return self.generated_marker in note_path.read_text(
            encoding="utf-8", errors="replace"
        )

    def _write_daily_note(self, date: str, content: str) -> bool:
        notes_dir = self.vault_manager.vault_root / "daily_notes"
        notes_dir.mkdir(parents=True, exist_ok=True)
        note_path = notes_dir / f"{date}.md"
        if note_path.exists():
            existing_content = note_path.read_text(encoding="utf-8", errors="replace")
            if self.generated_marker in existing_content:
                print(f"ℹ️ Keeping existing generated daily note: {date}")
                return False
            raise FileExistsError(
                f"Refusing to overwrite unmarked daily note: {note_path}"
            )
        note_path.write_text(content, encoding="utf-8")
        return True

    def _synthesize_journal(self, prompt: str, date: str, part: int) -> Dict[str, object]:
        last_error = None
        for attempt in range(1, 4):
            try:
                summary = json.loads(self.synthesizer.synthesize_for_journal(prompt))
                return summary
            except (json.JSONDecodeError, KeyError, SynthesizerError) as error:
                last_error = error
                if attempt < 3:
                    print(
                        f"⚠️ Retrying {date} part {part} after model error: {error}"
                    )
        try:
            print(
                f"⚠️ Using narrative fallback for {date} part {part} "
                f"after structured-output errors: {last_error}"
            )
            narrative = self.synthesizer.synthesize_session(
                {
                    "session_raw_log": prompt,
                    "trigger_commit": f"Historical daily note for {date}",
                    "repository": "multiple repositories",
                }
            )
            return {
                "summary": narrative,
                "sections": [
                    {
                        "title": f"Historical activity, part {part}",
                        "work_done": narrative,
                        "went_well": "Not recorded.",
                        "learned": "Not recorded.",
                        "remember": "Review the source session for detail.",
                        "commits": [],
                    }
                ],
            }
        except SynthesizerError as error:
            raise SynthesizerError(
                f"structured and narrative synthesis failed: {error}"
            ) from error

    def run(
        self,
        days: int = 14,
        replace_generated: bool = False,
        dates: Iterable[str] = None,
    ) -> int:
        if days <= 0:
            raise ValueError("days must be a positive integer")

        since = datetime.now(timezone.utc) - timedelta(days=days)
        events = [
            event
            for driver in self.drivers
            for event in driver.history_since(since)
        ]
        events_by_date, skipped_events = self._group_events_by_date(events)
        repositories = self._repositories(self.config.SEARCH_DIR)
        date_strings = {
            (since + timedelta(days=offset)).date().isoformat()
            for offset in range(days + 1)
        }
        commits_by_date = {
            date: self._commits_for_date(repositories, date) for date in date_strings
        }
        for date, commits in commits_by_date.items():
            for commit in commits:
                self.vault_manager.write_commit_note(
                    commit["project"], commit["id"], commit["title"], date
                )
        target_dates = sorted(
            date
            for date in date_strings
            if events_by_date.get(date) or commits_by_date.get(date)
        )
        if dates is not None:
            requested_dates = set(dates)
            target_dates = [
                date for date in target_dates if date in requested_dates
            ]
        removed = (
            self._remove_generated_notes(target_dates)
            if replace_generated
            else 0
        )
        print(
            f"🧹 Removed {removed} prior Autograph daily notes. "
            f"Generating {len(target_dates)} historical daily notes."
        )
        if skipped_events:
            print(f"⚠️ Skipped {skipped_events} session events without timestamps.")

        created = 0
        for date in target_dates:
            if self._has_generated_note(date):
                print(f"ℹ️ Keeping existing generated daily note: {date}")
                continue
            chunks = self._event_chunks(events_by_date.get(date, [])) or [[]]
            print(f"📝 Generating {date} from {len(chunks)} session chunks.")
            chunk_results = []
            for index, chunk in enumerate(chunks, start=1):
                events_text = "\n".join(
                    json.dumps(event, ensure_ascii=False) for event in chunk
                )
                commits_text = (
                    "\n".join(
                        f"{commit['id']}: {commit['title']} ({commit['project']})"
                        for commit in commits_by_date[date]
                    )
                    if index == 1
                    else ""
                )
                prompt = (
                    f"Date: {date}\n\n"
                    f"Git commits:\n{commits_text or 'None recorded'}\n\n"
                    f"Agent session activity:\n{events_text or 'None recorded'}"
                )
                try:
                    chunk_results.append(self._synthesize_journal(prompt, date, index))
                except SynthesizerError as error:
                    print(f"❌ Could not generate {date} part {index}: {error}")

            if not chunk_results:
                continue
            summaries = "\n".join(
                str(result["summary"]) for result in chunk_results
            )
            try:
                day_summary = self.synthesizer.synthesize_day_overview(date, summaries)
            except SynthesizerError as error:
                print(f"⚠️ Could not create single day summary for {date}: {error}")
                day_summary = summaries
            sections = [
                section
                for result in chunk_results
                for section in result["sections"]
                if isinstance(section, dict)
            ]
            content = render_daily_note(
                date,
                day_summary,
                sections,
                commits_by_date[date],
                [
                    candidate
                    for candidate in (
                        target_dates[
                            max(0, target_dates.index(date) - 1)
                        ],
                        target_dates[
                            min(len(target_dates) - 1, target_dates.index(date) + 1)
                        ],
                    )
                    if candidate != date
                ],
            )
            try:
                wrote_note = self._write_daily_note(date, content)
            except FileExistsError as error:
                print(f"⚠️ {error}")
                continue
            if wrote_note:
                created += 1
                print(f"✅ Created historical daily note: {date}")

        print(f"✅ Created {created} historical daily notes.")
        if created:
            self.sync_agent.sync()
        return created
