import os
import subprocess
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Dict, Iterable, List, Tuple

from config.settings import Config
from src.agents.sync_agent import AutographSyncAgent
from src.core.daily_note_renderer import render_daily_note, session_note_link
from src.core.daily_note_state import DailyNoteState
from src.core.drivers.jsonl_session_driver import (
    ClaudeDriver,
    CodexDriver,
    CopilotDriver,
    JsonlSessionDriver,
    PiDriver,
)
from src.core.synthesizer import Synthesizer, SynthesizerError
from src.core.vault import VaultManager
from src.core.work_units import (
    Commit,
    WorkUnit,
    build_work_units,
    fingerprint_work_day,
    normalize_events,
)


class DailyBackfillAgent:
    """Creates concise date-specific daily notes from retained local work records."""

    generated_marker = "*Generated by Autograph Agent*"

    def __init__(self):
        self.config = Config()
        self.vault_manager = VaultManager(self.config.VAULT_ROOT)
        self.synthesizer = Synthesizer()
        self.sync_agent = AutographSyncAgent(self.vault_manager.vault_root)
        self.state = DailyNoteState(self.config.LOG_DIR / "daily_note_state.json")
        self.drivers = [
            CopilotDriver("copilot", self.config),
            ClaudeDriver("claude", self.config),
            CodexDriver("codex", self.config),
            PiDriver("pi", self.config),
        ]

    @staticmethod
    def _repositories(search_dir: Path) -> List[Path]:
        repositories = []
        for root, directories, _ in os.walk(search_dir):
            if ".git" in directories:
                repositories.append(Path(root))
                directories.remove(".git")
            directories[:] = [
                directory
                for directory in directories
                if directory not in {"node_modules", "__pycache__", ".venv"}
            ]
        return repositories

    @staticmethod
    def _commits_since(
        repositories: Iterable[Path], since: datetime, until: datetime
    ) -> List[Commit]:
        commits = []
        for repository in repositories:
            try:
                result = subprocess.run(
                    [
                        "git",
                        "-C",
                        str(repository),
                        "log",
                        f"--since={since.isoformat()}",
                        f"--until={until.isoformat()}",
                        "--pretty=format:%H%x00%aI%x00%s%x00",
                    ],
                    capture_output=True,
                    text=True,
                    check=True,
                )
            except subprocess.CalledProcessError as error:
                print(f"⚠️ Could not read commits from {repository.name}: {error}")
                continue

            fields = result.stdout.split("\0")
            for index in range(0, len(fields) - 2, 3):
                commit_id, timestamp, title = fields[index:index + 3]
                # git log separates records with a newline, so every id after the
                # first arrives with one attached and would break its wikilink.
                commit_id = commit_id.strip()
                try:
                    commit_time = datetime.fromisoformat(
                        timestamp.replace("Z", "+00:00")
                    ).astimezone(timezone.utc)
                except ValueError:
                    continue
                commits.append(
                    Commit(
                        id=commit_id,
                        title=title,
                        project=repository.name,
                        timestamp=commit_time,
                    )
                )
        return commits

    @staticmethod
    def _commits_for_date(
        repositories: Iterable[Path], date: str
    ) -> List[Dict[str, str]]:
        start = datetime.fromisoformat(date).replace(tzinfo=timezone.utc)
        return [
            {"id": commit.id, "title": commit.title, "project": commit.project}
            for commit in DailyBackfillAgent._commits_since(
                repositories, start, start + timedelta(days=1)
            )
        ]

    def _remove_generated_notes(self, dates: Iterable[str] = None) -> int:
        notes_dir = self.vault_manager.vault_root / "daily_notes"
        if not notes_dir.exists():
            return 0

        target_dates = set(dates) if dates is not None else None
        removed = 0
        for note_path in notes_dir.glob("*.md"):
            if target_dates is not None and note_path.stem not in target_dates:
                continue
            content = note_path.read_text(encoding="utf-8", errors="replace")
            if self.generated_marker in content:
                note_path.unlink()
                removed += 1
        return removed

    def _has_generated_note(self, date: str) -> bool:
        note_path = self.vault_manager.vault_root / "daily_notes" / f"{date}.md"
        return note_path.exists() and self.generated_marker in note_path.read_text(
            encoding="utf-8", errors="replace"
        )

    def _write_daily_note(self, date: str, content: str) -> bool:
        notes_dir = self.vault_manager.vault_root / "daily_notes"
        notes_dir.mkdir(parents=True, exist_ok=True)
        note_path = notes_dir / f"{date}.md"
        if note_path.exists():
            existing_content = note_path.read_text(encoding="utf-8", errors="replace")
            if self.generated_marker not in existing_content:
                raise FileExistsError(
                    f"Refusing to overwrite unmarked daily note: {note_path}"
                )
        note_path.write_text(content, encoding="utf-8")
        return True

    @staticmethod
    def _section_summary(section: Dict[str, object]) -> str:
        return (
            f"{section['title']}: {section['work_done']} "
            f"Learning: {section['learned']} "
            f"Remember: {section['remember']}"
        )

    def _sections_for_units(
        self,
        date: str,
        units: List[WorkUnit],
        session_metadata: Dict[Tuple[str, str], Dict[str, object]] = None,
    ) -> List[Dict[str, object]]:
        session_metadata = session_metadata or {}
        sections = []
        for index, unit in enumerate(units, start=1):
            try:
                section = self.synthesizer.synthesize_work_unit(unit.prompt())
            except SynthesizerError as error:
                print(f"❌ Could not generate {date} work unit {index}: {error}")
                continue
            section["project"] = unit.project
            section["source"] = unit.source
            section["commits"] = [commit.id for commit in unit.commits]
            metadata = session_metadata.get((unit.source, unit.session_id))
            if metadata is not None:
                # Only identified sessions are linkable: codex and pi units fall
                # back to a directory name that names a day or a cwd, not a session.
                section["session_id"] = unit.session_id
                section["models"] = metadata.get("models", [])
            sections.append(section)
        return sections

    def _write_session_notes(
        self,
        sections: Iterable[Dict[str, object]],
        session_metadata: Dict[Tuple[str, str], Dict[str, object]],
    ) -> int:
        """Create the session stubs the rendered daily note links to."""
        written = 0
        for section in sections:
            source = section.get("source")
            session_id = section.get("session_id")
            if not isinstance(source, str) or not session_note_link(source, session_id):
                continue
            metadata = session_metadata.get((source, session_id), {})
            written += bool(
                self.vault_manager.write_session_note(
                    source,
                    str(session_id),
                    metadata.get("models"),
                    metadata.get("transcript"),
                )
            )
        return written

    def run(
        self,
        days: int = 14,
        replace_generated: bool = False,
        dates: Iterable[str] = None,
    ) -> int:
        if days <= 0:
            raise ValueError("days must be a positive integer")

        until = datetime.now(timezone.utc)
        since = (until - timedelta(days=days)).replace(
            hour=0, minute=0, second=0, microsecond=0
        )
        repositories = self._repositories(self.config.SEARCH_DIR)
        raw_events = [
            event
            for driver in self.drivers
            for event in driver.history_since(since)
        ]
        events = normalize_events(
            raw_events, repositories, JsonlSessionDriver._parse_timestamp
        )
        session_metadata: Dict[Tuple[str, str], Dict[str, object]] = {}
        for driver in self.drivers:
            for session_id, metadata in driver.session_metadata(since).items():
                session_metadata[(driver.source_name, session_id)] = metadata
        commits = self._commits_since(repositories, since, until)
        units_by_date = build_work_units(events, commits)
        commits_by_date: Dict[str, List[Commit]] = {}
        for commit in commits:
            commits_by_date.setdefault(commit.timestamp.date().isoformat(), []).append(
                commit
            )

        target_dates = sorted(units_by_date)
        if dates is not None:
            target_dates = [date for date in target_dates if date in set(dates)]
        if replace_generated:
            removed = self._remove_generated_notes(target_dates)
            print(f"🧹 Removed {removed} prior Autograph daily notes.")

        print(
            f"🔍 Retained {len(events)} meaningful events in "
            f"{sum(len(units) for units in units_by_date.values())} work units."
        )
        created = 0
        for date in target_dates:
            units = units_by_date[date]
            day_commits = commits_by_date.get(date, [])
            fingerprint = fingerprint_work_day(units, day_commits)
            if self._has_generated_note(date) and self.state.is_current(
                date, fingerprint
            ):
                print(f"ℹ️ Daily note is current: {date}")
                continue

            for project in {unit.project for unit in units if unit.project != "unassigned"}:
                self.vault_manager.write_project_note(project)
            for commit in day_commits:
                self.vault_manager.write_project_note(commit.project)
                self.vault_manager.write_commit_note(
                    commit.project, commit.id, commit.title, date
                )

            print(f"📝 Generating {date} from {len(units)} work units.")
            sections = self._sections_for_units(date, units, session_metadata)
            if not sections:
                continue
            self._write_session_notes(sections, session_metadata)
            try:
                summary = self.synthesizer.synthesize_day_overview(
                    date,
                    "\n".join(self._section_summary(section) for section in sections),
                )
            except SynthesizerError as error:
                print(f"⚠️ Could not generate overview for {date}: {error}")
                summary = self._section_summary(sections[0])

            content = render_daily_note(
                date,
                summary,
                sections,
                [
                    {"id": commit.id, "title": commit.title, "project": commit.project}
                    for commit in day_commits
                ],
                [
                    candidate
                    for candidate in (
                        target_dates[max(0, target_dates.index(date) - 1)],
                        target_dates[
                            min(len(target_dates) - 1, target_dates.index(date) + 1)
                        ],
                    )
                    if candidate != date
                ],
            )
            try:
                self._write_daily_note(date, content)
            except FileExistsError as error:
                print(f"⚠️ {error}")
                continue
            self.state.save(date, fingerprint)
            created += 1
            print(f"✅ Created historical daily note: {date}")

        print(f"✅ Created {created} historical daily notes.")
        if created:
            self.sync_agent.sync()
        return created
