from datetime import datetime, timedelta, timezone
from typing import Dict, Iterable, List

from config.settings import Config
from src.agents.daily_backfiller import DailyBackfillAgent
from src.agents.sync_agent import AutographSyncAgent
from src.core.daily_note_renderer import render_graph_connections
from src.core.drivers.jsonl_session_driver import JsonlSessionDriver
from src.core.work_units import build_work_units, normalize_events


class DailyNoteLinker:
    """Connect existing generated daily notes to their verified source nodes."""

    generated_marker = "*Generated by Autograph Agent*"

    def __init__(self):
        self.daily_backfill = DailyBackfillAgent()
        self.vault_manager = self.daily_backfill.vault_manager
        self.sync_agent = AutographSyncAgent(self.vault_manager.vault_root)

    @staticmethod
    def _insert_connections(content: str, connections: str) -> str:
        if not connections:
            return content
        marker = "\n---\n*Generated by Autograph Agent*"
        if marker not in content:
            raise ValueError("Generated daily note has no Autograph marker")
        return content.replace(marker, f"\n\n{connections}{marker}")

    def run(self, days: int = 14) -> int:
        if days <= 0:
            raise ValueError("days must be a positive integer")

        since = datetime.now(timezone.utc) - timedelta(days=days)
        repositories = self.daily_backfill._repositories(Config.SEARCH_DIR)
        raw_events = [
            event
            for driver in self.daily_backfill.drivers
            for event in driver.history_since(since)
        ]
        events = normalize_events(
            raw_events, repositories, JsonlSessionDriver._parse_timestamp
        )
        commits = self.daily_backfill._commits_since(
            repositories, since, datetime.now(timezone.utc)
        )
        units_by_date = build_work_units(events, commits)
        commits_by_date: Dict[str, List[Dict[str, str]]] = {}
        for commit in commits:
            self.vault_manager.write_project_note(commit.project)
            self.vault_manager.write_commit_note(
                commit.project,
                commit.id,
                commit.title,
                commit.timestamp.date().isoformat(),
            )
            commits_by_date.setdefault(commit.timestamp.date().isoformat(), []).append(
                {"id": commit.id, "title": commit.title, "project": commit.project}
            )

        updated = 0
        notes_dir = self.vault_manager.vault_root / "daily_notes"
        for note_path in sorted(notes_dir.glob("*.md")):
            content = note_path.read_text(encoding="utf-8", errors="replace")
            if self.generated_marker not in content:
                continue
            date = note_path.stem
            sources = [
                unit.source for unit in units_by_date.get(date, [])
                if unit.source != "git"
            ]
            connections = render_graph_connections(
                sources, commits_by_date.get(date, []), content
            )
            updated_content = self._insert_connections(content, connections)
            if updated_content != content:
                note_path.write_text(updated_content, encoding="utf-8")
                updated += 1

        print(f"🔗 Connected {updated} generated daily notes to graph nodes.")
        if updated:
            self.sync_agent.sync()
        return updated
