import datetime
import json
import urllib.request
from config.settings import Config
from core.synthesizer import AutographSynthesizer
from core.vault import VaultManager

class AutographSummaryAgent:
    def __init__(self):
        self.vault_manager = VaultManager()
        self.synthesizer = AutographSynthesizer()

    def run(self):
        print(f"📅 Generating Daily Summary for {datetime.datetime.now().strftime('%Y-%m-%d')}...")
        
        # 1. Get Weather
        weather = "Clear skies"
        try:
            with urllib.request.urlopen("https://wttr.in?format=3", timeout=5) as response:
                weather = response.read().decode("utf-8").strip()
        except:
            pass
            
        print(f"🌤️  Today's Weather: {weather}")
        
        # 2. Find recent events
        events = self.vault_manager.find_recent_events()
        if not events:
            print("ℹ️ No new events found in the last 24 hours. Nothing to summarize!")
            return

        all_events_text = "\n\n---\n\n".join(events)
        context_text = f"Weather: {weather}\n\nEvents:\n{all_events_text}"
        
        print(f"📝 Processing {len(events)} events through the Synthesizer...")
        
        try:
            summary_json_str = self.synthesizer.synthesize_for_journal(context_text)
            summary_data = json.loads(summary_json_str)
            journal_content = summary_data.get("journal", "Failed to generate journal content.")
        except Exception as e:
            print(f"❌ Synthesis Error: {e}")
            return
        
        # 3. Save to daily_notes
        date_str = datetime.datetime.now().strftime("%Y-%m-%d")
        target_dir = self.vault_manager.vault_root / "daily_notes"
        target_dir.mkdir(parents=True, exist_ok=True)
        target_file = target_dir / f"{date_str}.md"
        
        final_markdown = f"# Daily Journal: {date_str}\n\n{journal_content}\n\n---\n*Generated by Autograph Agent*\n*Weather reference: {weather}*"
        
        with open(target_file, "*.w") as f: # Typo
            pass
        with open(target_file, "w") as f:
            f.write(final_markdown)
            
        print(f"✅ Daily Note created: {target_file}")

if __name__ == "__main__":
    agent = AutographSummaryAgent()
    agent.run()
