import datetime
import json

from config.settings import Config
from src.agents.daily_backfiller import DailyBackfillAgent
from src.agents.sync_agent import AutographSyncAgent
from src.core.daily_note_renderer import related_daily_dates, render_daily_note
from src.core.synthesizer import Synthesizer, SynthesizerError
from src.core.vault import VaultManager

class AutographSummaryAgent:
    def __init__(self):
        self.vault_manager = VaultManager()
        self.synthesizer = Synthesizer()
        self.sync_agent = AutographSyncAgent(self.vault_manager.vault_root)

    def run(self):
        print(f"📅 Generating Daily Summary for {datetime.datetime.now().strftime('%Y-%m-%d')}...")

        events = self.vault_manager.find_recent_events()
        if not events:
            print("ℹ️ No new events found in the last 24 hours. Nothing to summarize!")
        else:
            all_events_text = "\n\n---\n\n".join(events)
            date_str = datetime.datetime.now().strftime("%Y-%m-%d")
            commits = DailyBackfillAgent._commits_for_date(
                DailyBackfillAgent._repositories(Config.SEARCH_DIR), date_str
            )
            for commit in commits:
                self.vault_manager.write_commit_note(
                    commit["project"], commit["id"], commit["title"], date_str
                )
            context_text = (
                f"Date: {date_str}\n\nGit commits:\n"
                + "\n".join(
                    f"{commit['id']}: {commit['title']} ({commit['project']})"
                    for commit in commits
                )
                + f"\n\nEvents:\n{all_events_text}"
            )
            print(f"📝 Processing {len(events)} events through the Synthesizer...")

            try:
                summary_json_str = self.synthesizer.synthesize_for_journal(context_text)
                summary_data = json.loads(summary_json_str)
                journal_content = render_daily_note(
                    date_str,
                    summary_data["summary"],
                    summary_data["sections"],
                    commits,
                    related_daily_dates(
                        self.vault_manager.vault_root / "daily_notes", date_str
                    ),
                )
                target_dir = self.vault_manager.vault_root / "daily_notes"
                target_dir.mkdir(parents=True, exist_ok=True)
                target_file = target_dir / f"{date_str}.md"
                if target_file.exists() and (
                    "*Generated by Autograph Agent*"
                    not in target_file.read_text(encoding="utf-8")
                ):
                    print(f"⚠️ Refusing to overwrite manual note: {target_file}")
                    return
                target_file.write_text(journal_content, encoding="utf-8")
                print(f"✅ Daily Note created: {target_file}")
            except (json.JSONDecodeError, KeyError, SynthesizerError) as e:
                print(f"❌ Synthesis Error: {e}")

        print("\n🔄 Triggering Vault Synchronization...")
        self.sync_agent.sync()

if __name__ == "__main__":
    agent = AutographSummaryAgent()
    agent.run()
